version: '3.8'

services:
  angular-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production